use_small_heuristics = "Max"
newline_style = "unix"
use_field_init_shorthand = true

format_macro_matchers = true
format_macro_bodies = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
